FROM ubuntu:18.04
LABEL maintainer lei.wang@cvitek.com

# Use cn.archive.ubuntu.com apt source;
COPY sources-18.04.list /etc/apt/sources.list

# ================== apt ==================
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gdb \
    ninja-build \
    automake \
    autoconf \
    libtool \
    vim \
    wget \
    curl \
    git \
    parallel \
    ssh-client \
    unzip \
    python-dev \
    python-pip \
    python-setuptools \
    python3-dev \
    python3-pip \
    python3-setuptools

# bsp tools
RUN apt-get install -y --no-install-recommends \
    device-tree-compiler \
    libssl-dev \
    ssh \
    bc \
    slib \
    cpio \
    squashfs-tools \
    fakeroot

# gst build
RUN apt-get install -y --no-install-recommends \
    pkg-config \
    autopoint \
    bison \
    flex \
    gettext \
    indent \
    meson \
    libglib2.0-dev \
    clang-format

# for caffe build
RUN apt-get install -y --no-install-recommends \
    libboost-all-dev \
    libgflags-dev \
    libgoogle-glog-dev \
    libhdf5-serial-dev \
    libleveldb-dev \
    liblmdb-dev \
    libprotobuf-dev \
    libsnappy-dev \
    protobuf-compiler \
    libopenblas-dev

# for cmake
RUN apt-get install -y --no-install-recommends \
    apt-transport-https \
    ca-certificates \
    gnupg \
    software-properties-common
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | apt-key add -
RUN apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake-data=3.16.5-0kitware1 \
    cmake=3.16.5-0kitware1

# restore source again
COPY sources-18.04.list /etc/apt/sources.list

# cleanup
RUN rm -rf /var/lib/apt/lists/*

# ================== pip ==================
RUN pip install --upgrade pip
# RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple
RUN pip install --no-cache-dir \
    Cython \
    numpy \
    scipy \
    scikit-image==0.14 \
    matplotlib \
    wheel \
    leveldb \
    decorator \
    networkx==2.2 \
    nose \
    python-dateutil \
    protobuf \
    pyyaml \
    Pillow \
    six \
    lmdb \
    future \
    pathlib \
    tqdm \
    enum34 \
    termcolor \
    opencv-python-headless \
    PyWavelets==1.0.3 \
    torch \
    torchvision \
    onnx

RUN pip3 install --upgrade pip
# RUN pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 config set global.index-url https://mirrors.aliyun.com/pypi/simple
RUN pip3 install --no-cache-dir \
    Cython \
    numpy \
    scipy \
    scikit-image \
    matplotlib \
    wheel \
    leveldb \
    decorator \
    networkx \
    nose \
    python-dateutil \
    protobuf \
    pyyaml \
    Pillow \
    six \
    lmdb \
    pathlib \
    tqdm \
    enum34 \
    termcolor \
    opencv-python-headless \
    torch \
    torchvision \
    onnxruntime

# cocoAPI, pip install has conflict with latest numpy,
RUN git clone https://github.com/cocodataset/cocoapi.git \
    && cd cocoapi/PythonAPI && make -j8 \
    && python2 setup.py install \
    && python3 setup.py install

# ================== toolchain ====================
COPY host-tools/gcc/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu \
    /host-tools/gcc/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu
ENV PATH=/host-tools/gcc/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/bin:$PATH
COPY host-tools/gcc/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf \
    /host-tools/gcc/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf
ENV PATH=/host-tools/gcc/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/bin:$PATH

# ================== zoneinfo ==================
COPY zoneinfo/PRC /usr/share/zoneinfo/PRC
# Set time zone to Asia/Shanghai;
ENV TZ=Asia/Shanghai
# make timezone links and conf
RUN mkdir /usr/share/zoneinfo/Asia \
  && ln -snf /usr/share/zoneinfo/PRC /usr/share/zoneinfo/$TZ \
  && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
  && echo $TZ > /etc/timezone

# ================== envs ==================
RUN echo 'alias pip="pip3"' >> ~/.bashrc
RUN echo 'alias python="python3"' >> ~/.bashrc
ENV MODEL_PATH=/work/models
ENV DATASET_PATH=/work/dataset

WORKDIR /work/
